volumes:
  db:

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 3001:3000
      - 9876:9876
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
